spring.application.name=tiendavirtual
# ===============================
# Configuraci\u00f3n de la base de datos
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/tiendavirtual?useSSL=false&serverTimezone=UTC
spring.datasource.username=TU_USUARIO
spring.datasource.password=TU_CONTRASE\u00d1A_MYSQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# Configuraci\u00f3n de JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ===============================
# Puerto de la aplicaci\u00f3n
# ===============================
server.port=8080

# ===============================
# Perfil activo
# ===============================
spring.profiles.active=default

server.error.include-message=always

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true